version: "3.8"

services:
  stonks-api:
    build:
      context: .
      dockerfile: ./docker/stonks-api.dev.Dockerfile
    container_name: stonks-api
    ports:
    - 8000:8000
    depends_on:
    - stonks-database
    volumes:
    - ./stonks-api:/app/stonks-api
    environment:
      - DATABASE_URL=postgresql://lomber:root@stonks-database:5432/stonks

  stonks-database:
    image: postgres:13
    container_name: stonks-database
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=lomber
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=stonks
    volumes:
    - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - stonks-database
    ports:
    - 8080:8080

volumes:
  postgres_data:
