"""empty message

Revision ID: 04b34de44cf2
Revises: 33b8c293768f
Create Date: 2021-05-01 15:41:02.537611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b34de44cf2'
down_revision = '33b8c293768f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'origin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('origin', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
