"""empty message

Revision ID: 0a45b4e8696a
Revises: 9094d232d7f3
Create Date: 2021-04-18 16:44:26.599968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a45b4e8696a'
down_revision = '9094d232d7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offers_price_id_fkey', 'offers', type_='foreignkey')
    op.drop_column('offers', 'price_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('price_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('offers_price_id_fkey', 'offers', 'price', ['price_id'], ['id'])
    # ### end Alembic commands ###
