"""empty message

Revision ID: 0cc6ca305279
Revises: 847e5692b5c6
Create Date: 2021-04-18 21:45:55.282186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc6ca305279'
down_revision = '847e5692b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
