"""empty message

Revision ID: 0e9a41c06ff8
Revises: 0a0919de62aa
Create Date: 2021-04-18 16:54:30.892968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9a41c06ff8'
down_revision = '0a0919de62aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee', sa.Column('amount', sa.Numeric(precision=4), nullable=False))
    op.add_column('fee', sa.Column('currency', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee', 'currency')
    op.drop_column('fee', 'amount')
    # ### end Alembic commands ###
