"""empty message

Revision ID: 141c44e6fc58
Revises: 61bb7449886a
Create Date: 2021-04-18 21:33:03.500295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141c44e6fc58'
down_revision = '61bb7449886a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
