"""empty message

Revision ID: 1438f801cfb5
Revises: de926f2154d2
Create Date: 2021-05-02 19:21:34.714008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1438f801cfb5'
down_revision = 'de926f2154d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'date')
    # ### end Alembic commands ###
