"""empty message

Revision ID: 1ac5dda85e68
Revises: 5de697906da7
Create Date: 2021-04-18 22:02:30.606482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ac5dda85e68'
down_revision = '5de697906da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('last_refresh_time', sa.DateTime(), nullable=True))
    op.add_column('offer', sa.Column('last_scraped_time', sa.DateTime(), nullable=False))
    op.add_column('offer', sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('offer', sa.Column('url', sa.String(), nullable=True))
    op.alter_column('offer', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('offer', 'url')
    op.drop_column('offer', 'photos')
    op.drop_column('offer', 'last_scraped_time')
    op.drop_column('offer', 'last_refresh_time')
    # ### end Alembic commands ###
