"""empty message

Revision ID: 26bb7fa411ff
Revises: 141c44e6fc58
Create Date: 2021-04-18 21:37:38.462588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bb7fa411ff'
down_revision = '141c44e6fc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
