"""empty message

Revision ID: 2ed05bf2aceb
Revises: 0e9a41c06ff8
Create Date: 2021-04-18 16:56:22.098569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed05bf2aceb'
down_revision = '0e9a41c06ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stonks',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fee', sa.Column('stonks_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fee', 'stonks', ['stonks_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee', type_='foreignkey')
    op.drop_column('fee', 'stonks_id')
    op.drop_table('stonks')
    # ### end Alembic commands ###
