"""empty message

Revision ID: 319de83a74a1
Revises: b34448f534fd
Create Date: 2021-04-18 16:49:23.633399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319de83a74a1'
down_revision = 'b34448f534fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fee_price_id_fkey', 'fee', type_='foreignkey')
    op.create_foreign_key(None, 'fee', 'price', ['price_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee', type_='foreignkey')
    op.create_foreign_key('fee_price_id_fkey', 'fee', 'price', ['price_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
