"""empty message

Revision ID: 32e368f17259
Revises: 399147180ee5
Create Date: 2021-04-18 16:21:55.539686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e368f17259'
down_revision = '399147180ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fee_offer_id_fkey', 'fee', type_='foreignkey')
    op.drop_constraint('fee_price_id_fkey', 'fee', type_='foreignkey')
    op.drop_column('fee', 'offer_id')
    op.drop_column('fee', 'price_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee', sa.Column('price_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fee', sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fee_price_id_fkey', 'fee', 'price', ['price_id'], ['id'])
    op.create_foreign_key('fee_offer_id_fkey', 'fee', 'offers', ['offer_id'], ['id'])
    # ### end Alembic commands ###
