"""empty message

Revision ID: 33b8c293768f
Revises: 961714a00c23
Create Date: 2021-05-01 15:20:27.758297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b8c293768f'
down_revision = '961714a00c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('origin', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'origin')
    # ### end Alembic commands ###
