"""empty message

Revision ID: 421050da1135
Revises: afb6a85f703b
Create Date: 2021-04-18 22:22:16.475524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421050da1135'
down_revision = 'afb6a85f703b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'price')
    op.drop_column('fee', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee', sa.Column('amount', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False))
    op.add_column('delivery', sa.Column('price', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
