"""empty message

Revision ID: 46512f11eb4c
Revises: 04b34de44cf2
Create Date: 2021-05-01 19:26:20.359203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46512f11eb4c'
down_revision = '04b34de44cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
