"""empty message

Revision ID: 47b0a110e734
Revises: d0317f4cb604
Create Date: 2021-04-18 21:42:07.311435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b0a110e734'
down_revision = 'd0317f4cb604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
