"""empty message

Revision ID: 4d50dca74025
Revises: 1438f801cfb5
Create Date: 2021-05-04 12:14:13.810934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d50dca74025'
down_revision = '1438f801cfb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('last_stonks_check', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'last_stonks_check')
    # ### end Alembic commands ###
