"""empty message

Revision ID: 54f751315a4f
Revises: 96e94afb9473
Create Date: 2021-04-18 16:52:00.381506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f751315a4f'
down_revision = '96e94afb9473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fee_price_id_fkey', 'fee', type_='foreignkey')
    op.drop_column('fee', 'price_id')
    op.drop_constraint('offers_price_id_fkey', 'offers', type_='foreignkey')
    op.drop_column('offers', 'price_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('price_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('offers_price_id_fkey', 'offers', 'price', ['price_id'], ['id'])
    op.add_column('fee', sa.Column('price_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fee_price_id_fkey', 'fee', 'price', ['price_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
