"""empty message

Revision ID: 5b33dce8fb1e
Revises: 0a45b4e8696a
Create Date: 2021-04-18 16:44:58.799004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b33dce8fb1e'
down_revision = '0a45b4e8696a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee', sa.Column('price_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fee', 'price', ['price_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee', type_='foreignkey')
    op.drop_column('fee', 'price_id')
    # ### end Alembic commands ###
