"""empty message

Revision ID: 5de69298f4e8
Revises: 9d1799e7e6fe
Create Date: 2021-04-26 10:30:28.761044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de69298f4e8'
down_revision = '9d1799e7e6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stonks', sa.Column('harmonic_price', sa.Numeric(precision=15, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stonks', 'harmonic_price')
    # ### end Alembic commands ###
