"""empty message

Revision ID: 61bb7449886a
Revises: 1053475814e3
Create Date: 2021-04-18 21:32:28.936833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bb7449886a'
down_revision = '1053475814e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
