"""empty message

Revision ID: 63aedd25aecd
Revises: 9b1f20938af8
Create Date: 2021-05-01 23:35:06.822397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63aedd25aecd'
down_revision = '9b1f20938af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('offer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_refresh_time', sa.DateTime(), nullable=True),
    sa.Column('last_scraped_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_name'], ['device.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'delivery', 'offer', ['offer_id'], ['id'], ondelete='CASCADE')
    op.add_column('price', sa.Column('device_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'price', 'device', ['device_name'], ['name'], ondelete='CASCADE')
    op.drop_column('price', 'device_id')
    op.create_foreign_key(None, 'stonks', 'offer', ['offer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stonks', type_='foreignkey')
    op.add_column('price', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.drop_column('price', 'device_name')
    op.drop_constraint(None, 'delivery', type_='foreignkey')
    op.drop_table('offer')
    op.drop_table('device')
    # ### end Alembic commands ###
