"""empty message

Revision ID: 768a34808cbf
Revises: 366a7d3431aa
Create Date: 2021-05-01 23:33:33.788467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768a34808cbf'
down_revision = '366a7d3431aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'id')
    op.add_column('offer', sa.Column('device_name', sa.Integer(), nullable=True))
    op.drop_constraint('offer_device_id_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'device', ['device_name'], ['name'], ondelete='SET NULL')
    op.drop_column('offer', 'device_id')
    op.add_column('price', sa.Column('device_name', sa.Integer(), nullable=False))
    op.drop_constraint('price_device_id_fkey', 'price', type_='foreignkey')
    op.create_foreign_key(None, 'price', 'device', ['device_name'], ['name'], ondelete='CASCADE')
    op.drop_column('price', 'device_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.create_foreign_key('price_device_id_fkey', 'price', 'device', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_column('price', 'device_name')
    op.add_column('offer', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_device_id_fkey', 'offer', 'device', ['device_id'], ['id'], ondelete='SET NULL')
    op.drop_column('offer', 'device_name')
    op.add_column('device', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('device_id_seq'::regclass)"), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
