"""empty message

Revision ID: 868992620776
Revises: c9e88602666b
Create Date: 2021-05-01 21:36:39.938080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868992620776'
down_revision = 'c9e88602666b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offer', 'device', ['device_id'], ['id'])
    op.drop_column('offer', 'device_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('device_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_column('offer', 'device_id')
    # ### end Alembic commands ###
