"""empty message

Revision ID: 9094d232d7f3
Revises: 32e368f17259
Create Date: 2021-04-18 16:42:07.347520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9094d232d7f3'
down_revision = '32e368f17259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('price_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offers', 'price', ['price_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'price_id')
    # ### end Alembic commands ###
