"""empty message

Revision ID: 961714a00c23
Revises: 5de69298f4e8
Create Date: 2021-04-30 22:14:34.290159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961714a00c23'
down_revision = '5de69298f4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('device_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'device_model')
    # ### end Alembic commands ###
