"""empty message

Revision ID: 96ac52900a01
Revises: 25d2251693fc
Create Date: 2021-04-18 22:15:54.583929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ac52900a01'
down_revision = '25d2251693fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
