"""empty message

Revision ID: 96e94afb9473
Revises: 319de83a74a1
Create Date: 2021-04-18 16:50:35.002097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e94afb9473'
down_revision = '319de83a74a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fee_price_id_fkey', 'fee', type_='foreignkey')
    op.create_foreign_key(None, 'fee', 'price', ['price_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee', type_='foreignkey')
    op.create_foreign_key('fee_price_id_fkey', 'fee', 'price', ['price_id'], ['id'])
    # ### end Alembic commands ###
