"""empty message

Revision ID: 9d1799e7e6fe
Revises: bae0ff55d81b
Create Date: 2021-04-24 03:15:01.038133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1799e7e6fe'
down_revision = 'bae0ff55d81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'is_active')
    # ### end Alembic commands ###
