"""empty message

Revision ID: a07a83ed099c
Revises: 63aedd25aecd
Create Date: 2021-05-01 23:53:13.871351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07a83ed099c'
down_revision = '63aedd25aecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offer_device_name_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'device', ['device_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_device_name_fkey', 'offer', 'device', ['device_name'], ['name'], ondelete='SET NULL')
    # ### end Alembic commands ###
