"""empty message

Revision ID: a07b05d52839
Revises: 2ed05bf2aceb
Create Date: 2021-04-18 17:00:57.688413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07b05d52839'
down_revision = '2ed05bf2aceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fee', 'stonks_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('offers', sa.Column('title', sa.String(), nullable=True))
    op.add_column('stonks', sa.Column('offer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stonks', 'offers', ['offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stonks', type_='foreignkey')
    op.drop_column('stonks', 'offer_id')
    op.drop_column('offers', 'title')
    op.alter_column('fee', 'stonks_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
