"""empty message

Revision ID: ae6eb6af96f6
Revises: a07b05d52839
Create Date: 2021-04-18 17:02:30.807498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6eb6af96f6'
down_revision = 'a07b05d52839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stonks_offer_id_fkey', 'stonks', type_='foreignkey')
    op.create_foreign_key(None, 'stonks', 'offers', ['offer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stonks', type_='foreignkey')
    op.create_foreign_key('stonks_offer_id_fkey', 'stonks', 'offers', ['offer_id'], ['id'])
    # ### end Alembic commands ###
