"""empty message

Revision ID: afb6a85f703b
Revises: 1f6d1cf51eaf
Create Date: 2021-04-18 22:21:56.095415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb6a85f703b'
down_revision = '1f6d1cf51eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('price', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
