"""empty message

Revision ID: aff28f230617
Revises: bb020b9a2fd7
Create Date: 2021-04-18 16:05:20.443795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff28f230617'
down_revision = 'bb020b9a2fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fee', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fee', 'offers', ['offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee', type_='foreignkey')
    op.drop_column('fee', 'offer_id')
    op.drop_table('offers')
    # ### end Alembic commands ###
