"""empty message

Revision ID: b002c603fdb7
Revises: 421050da1135
Create Date: 2021-04-18 22:22:42.438068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b002c603fdb7'
down_revision = '421050da1135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=False))
    op.add_column('fee', sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee', 'amount')
    op.drop_column('delivery', 'price')
    # ### end Alembic commands ###
