"""empty message

Revision ID: b34448f534fd
Revises: f8d7a922b77f
Create Date: 2021-04-18 16:47:58.193696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34448f534fd'
down_revision = 'f8d7a922b77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fee_price_id_fkey', 'fee', type_='foreignkey')
    op.create_foreign_key(None, 'fee', 'price', ['price_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee', type_='foreignkey')
    op.create_foreign_key('fee_price_id_fkey', 'fee', 'price', ['price_id'], ['id'])
    # ### end Alembic commands ###
