"""empty message

Revision ID: b4cba3de429d
Revises: 868992620776
Create Date: 2021-05-01 22:30:26.418776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4cba3de429d'
down_revision = '868992620776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offer_device_id_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'device', ['device_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_device_id_fkey', 'offer', 'device', ['device_id'], ['id'])
    # ### end Alembic commands ###
