"""empty message

Revision ID: b5163878b215
Revises: a07a83ed099c
Create Date: 2021-05-01 23:56:52.642268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5163878b215'
down_revision = 'a07a83ed099c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offer_device_name_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'device', ['device_name'], ['name'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_device_name_fkey', 'offer', 'device', ['device_name'], ['name'])
    # ### end Alembic commands ###
