"""empty message

Revision ID: bae0ff55d81b
Revises: cdfabc4ac843
Create Date: 2021-04-20 16:32:20.679517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae0ff55d81b'
down_revision = 'cdfabc4ac843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
