"""empty message

Revision ID: bb020b9a2fd7
Revises: 4c5674e7f6dd
Create Date: 2021-04-18 16:00:30.064453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb020b9a2fd7'
down_revision = '4c5674e7f6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee', sa.Column('price_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fee', 'price', ['price_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee', type_='foreignkey')
    op.drop_column('fee', 'price_id')
    # ### end Alembic commands ###
