"""empty message

Revision ID: c9e88602666b
Revises: 46512f11eb4c
Create Date: 2021-05-01 19:29:45.715259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e88602666b'
down_revision = '46512f11eb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'price', 'device', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.drop_column('price', 'device_id')
    # ### end Alembic commands ###
