"""empty message

Revision ID: cc01b20b6a78
Revises: 96ac52900a01
Create Date: 2021-04-18 22:16:22.374090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc01b20b6a78'
down_revision = '96ac52900a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stonks', 'median_price')
    op.drop_column('stonks', 'low_price')
    op.drop_column('stonks', 'average_price')
    op.drop_column('stonks', 'high_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stonks', sa.Column('high_price', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False))
    op.add_column('stonks', sa.Column('average_price', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False))
    op.add_column('stonks', sa.Column('low_price', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False))
    op.add_column('stonks', sa.Column('median_price', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
