"""empty message

Revision ID: d0317f4cb604
Revises: 26bb7fa411ff
Create Date: 2021-04-18 21:39:53.134164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0317f4cb604'
down_revision = '26bb7fa411ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
