"""empty message

Revision ID: de31857180d1
Revises: f0c984a3228c
Create Date: 2021-04-18 17:19:10.220568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de31857180d1'
down_revision = 'f0c984a3228c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    op.drop_constraint('offer_store_id_fkey', 'offer', type_='foreignkey')
    op.drop_column('offer', 'store_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('offer_store_id_fkey', 'offer', 'store', ['store_id'], ['id'])
    op.create_table('store',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='store_pkey')
    )
    # ### end Alembic commands ###
