"""empty message

Revision ID: f0c984a3228c
Revises: e940e6e00b3e
Create Date: 2021-04-18 17:16:12.756956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c984a3228c'
down_revision = 'e940e6e00b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offer', 'store', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_column('offer', 'store_id')
    # ### end Alembic commands ###
