"""empty message

Revision ID: f8d7a922b77f
Revises: 5b33dce8fb1e
Create Date: 2021-04-18 16:46:11.994303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d7a922b77f'
down_revision = '5b33dce8fb1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('price_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offers', 'price', ['price_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'price_id')
    # ### end Alembic commands ###
