"""Added category to device

Revision ID: 3a26ed71d58a
Revises: 6a7123981356
Create Date: 2021-05-20 19:54:25.729289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a26ed71d58a'
down_revision = '6a7123981356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'category')
    # ### end Alembic commands ###
