"""Updated stonks

Revision ID: 55cd444d7791
Revises: 3a26ed71d58a
Create Date: 2021-05-23 13:12:17.322894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cd444d7791'
down_revision = '3a26ed71d58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stonks', sa.Column('stonks_amount', sa.Numeric(precision=15, scale=4), nullable=False))
    op.add_column('stonks', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('stonks', 'low_price')
    op.drop_column('stonks', 'harmonic_price')
    op.drop_column('stonks', 'median_price')
    op.drop_column('stonks', 'average_price')
    op.drop_column('stonks', 'high_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stonks', sa.Column('high_price', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=False))
    op.add_column('stonks', sa.Column('average_price', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=False))
    op.add_column('stonks', sa.Column('median_price', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=False))
    op.add_column('stonks', sa.Column('harmonic_price', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=False))
    op.add_column('stonks', sa.Column('low_price', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=False))
    op.drop_column('stonks', 'is_active')
    op.drop_column('stonks', 'stonks_amount')
    # ### end Alembic commands ###
