"""Added last_update_at and renamed last_scraped_time to scraped_at.

Revision ID: 9030aa258427
Revises: f1295643f297
Create Date: 2021-05-13 11:47:59.783571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9030aa258427'
down_revision = 'f1295643f297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', "last_scraped_time", nullable=False, new_column_name="scraped_at")
    op.add_column('offer', sa.Column('last_update_at', sa.DateTime(), nullable=True))
    op.drop_column('offer', 'last_refresh_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', "scraped_at", nullable=False, new_column_name="last_scraped_time")
    op.drop_column('offer', 'last_update_at')
    op.add_column('offer', sa.Column('last_refresh_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
