version: "3.8"

services:
  broker:
    image: rabbitmq:3-management
    container_name: broker
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
